### ISSUE TITLE
Slow download speed on remote servers

### ISSUE THREAD

**Issue by mifiadmin** [jishan484/goDrive#5]
It is not a server issue or network issue.

Download speed is very slow.
highest speed was 500 Kbps.

TEST STEP:
    Download a file in localhost and try the same in remote server.
    File size : > 100MB
    Drive type: google
    
Expected result:
   Download speed to remote server is 10 times slower.

**Comment by jishan484** [comment]
Drive to server speed is ok.
server to client speed is very slow.

It is because of backpressure on that PassThrough stream.

One solution tested by increaing HighWaterMark of that stream. It solved that issue in glitch server.

**Comment by jishan484** [comment]
Not helping that much.. It is not using the full network bandwidth. Also using pipe to express response, nodejs app using too much CPU during download. During upload it is acceptable.

Plan: use direct download link. e.g. https://drive.google.com/u/6/uc?id=FILE_ID&export=download.

For fragmented files we can use pipe. We have to accept this, in this scenario, Also fragmented files upload is very rare.
